import { useState, useEffect } from "react";
import { useNavigate } from "react-router";
import { Upload, X, Eye, EyeOff } from "lucide-react";
import { api } from "../../lib/api";
import { toast } from "sonner";

interface Department {
  id: string;
  name: string;
}

interface Designation {
  id: string;
  name: string;
  departmentId: string;
}

export default function EmployeeCreate() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("basic");
  const [isLoading, setIsLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);

  const [departments, setDepartments] = useState<Department[]>([]);
  const [designations, setDesignations] = useState<Designation[]>([]);
  const [nextEmpId, setNextEmpId] = useState("EMP-0001");

  const [formData, setFormData] = useState({
    firstName: "",
    lastName: "",
    employeeId: "", // This will be auto-generated by backend, but we can show preview
    joiningDate: "",
    username: "",
    email: "",
    password: "",
    confirmPassword: "",
    phone: "",
    company: "",
    departmentId: "",
    designationId: "",
    about: "",
  });

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [depts, desigs, users] = await Promise.all([
          api.get("/departments"),
          api.get("/designations"),
          api.get("/users"),
        ]);
        setDepartments(depts);
        setDesignations(desigs);

        // Calculate next EMP ID for UI preview
        const lastEmp = users
          .filter((u: any) => u.employeeId?.startsWith("EMP-"))
          .sort((a: any, b: any) => b.createdAt.localeCompare(a.createdAt))[0];

        if (lastEmp && lastEmp.employeeId) {
          const num = parseInt(lastEmp.employeeId.replace("EMP-", ""), 10);
          setNextEmpId(`EMP-${String(num + 1).padStart(4, "0")}`);
        }
      } catch (error) {
        console.error("Failed to fetch form data", error);
      }
    };
    fetchData();
  }, []);

  const handleInputChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
    >,
  ) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (formData.password !== formData.confirmPassword) {
      return toast.error("Passwords do not match");
    }

    setIsLoading(true);
    try {
      await api.post("/users", {
        ...formData,
        role: "EMPLOYEE", // Default for this form
      });
      toast.success("Employee created successfully");
      navigate("/employees");
    } catch (error: any) {
      toast.error(error.message || "Failed to create employee");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="p-8 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div>
          <div className="flex items-center gap-2 text-gray-800">
            <h1 className="text-2xl font-bold">Add New Employee</h1>
            <span className="text-gray-500 font-medium ml-4">
              Employee ID : {nextEmpId}
            </span>
          </div>
        </div>
        <button
          onClick={() => navigate("/employees")}
          className="text-gray-400 hover:text-gray-600"
        >
          <X className="w-6 h-6" />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex gap-8 border-b border-gray-200 mb-8">
        <button
          onClick={() => setActiveTab("basic")}
          className={`pb-4 px-2 font-medium transition-colors relative ${
            activeTab === "basic"
              ? "text-[#1a5f3f]"
              : "text-gray-500 hover:text-gray-700"
          }`}
        >
          Basic Information
          {activeTab === "basic" && (
            <div className="absolute bottom-0 left-0 w-full h-0.5 bg-[#1a5f3f]" />
          )}
        </button>
        <button
          onClick={() => setActiveTab("permissions")}
          className={`pb-4 px-2 font-medium transition-colors relative ${
            activeTab === "permissions"
              ? "text-[#1a5f3f]"
              : "text-gray-500 hover:text-gray-700"
          }`}
        >
          Permissions
          {activeTab === "permissions" && (
            <div className="absolute bottom-0 left-0 w-full h-0.5 bg-[#1a5f3f]" />
          )}
        </button>
      </div>

      <form onSubmit={handleSubmit} className="space-y-8">
        {activeTab === "basic" && (
          <>
            {/* Profile Image Section */}
            <div className="bg-gray-50 rounded-xl p-8 flex items-center gap-8">
              <div className="w-24 h-24 bg-white border-2 border-dashed border-gray-200 rounded-full flex items-center justify-center text-gray-400">
                <Upload className="w-8 h-8" />
              </div>
              <div>
                <h3 className="text-[#1a5f3f] font-semibold mb-1 text-lg">
                  Upload Profile Image
                </h3>
                <p className="text-gray-500 text-sm mb-4">
                  Image should be below 4 mb
                </p>
                <div className="flex gap-3">
                  <button
                    type="button"
                    className="px-6 py-2 bg-[#ff6b35] text-white rounded-lg hover:bg-[#e85a20] transition-colors font-medium"
                  >
                    Upload
                  </button>
                  <button
                    type="button"
                    className="px-6 py-2 bg-white border border-gray-200 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors font-medium"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            </div>

            {/* Form Fields */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6">
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  First Name <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="firstName"
                  required
                  value={formData.firstName}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Last Name
                </label>
                <input
                  type="text"
                  name="lastName"
                  value={formData.lastName}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Employee ID <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  disabled
                  value={nextEmpId}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl bg-gray-50 text-gray-500 cursor-not-allowed"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Joining Date <span className="text-red-500">*</span>
                </label>
                <div className="relative">
                  <input
                    type="date"
                    name="joiningDate"
                    required
                    value={formData.joiningDate}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Username <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="username"
                  required
                  value={formData.username}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Email <span className="text-red-500">*</span>
                </label>
                <input
                  type="email"
                  name="email"
                  required
                  value={formData.email}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Password <span className="text-red-500">*</span>
                </label>
                <div className="relative">
                  <input
                    type={showPassword ? "text" : "password"}
                    name="password"
                    required
                    value={formData.password}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                  >
                    {showPassword ? (
                      <EyeOff className="w-5 h-5" />
                    ) : (
                      <Eye className="w-5 h-5" />
                    )}
                  </button>
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Confirm Password <span className="text-red-500">*</span>
                </label>
                <div className="relative">
                  <input
                    type={showConfirmPassword ? "text" : "password"}
                    name="confirmPassword"
                    required
                    value={formData.confirmPassword}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all"
                  />
                  <button
                    type="button"
                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                  >
                    {showConfirmPassword ? (
                      <EyeOff className="w-5 h-5" />
                    ) : (
                      <Eye className="w-5 h-5" />
                    )}
                  </button>
                </div>
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Phone Number <span className="text-red-500">*</span>
                </label>
                <input
                  type="tel"
                  name="phone"
                  required
                  value={formData.phone}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Company <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="company"
                  required
                  value={formData.company}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Department
                </label>
                <select
                  name="departmentId"
                  value={formData.departmentId}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all appearance-none bg-no-repeat bg-position-[right_1rem_center] bg-size-[1rem]"
                  style={{
                    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke='%239ca3af'%3E%3Cpath stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M19 9l-7 7-7-7'%3E%3C/path%3E%3C/svg%3E")`,
                  }}
                >
                  <option value="">Select</option>
                  {departments.map((dept) => (
                    <option key={dept.id} value={dept.id}>
                      {dept.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  Designation
                </label>
                <select
                  name="designationId"
                  value={formData.designationId}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all appearance-none bg-no-repeat bg-position-[right_1rem_center] bg-size-[1rem]"
                  style={{
                    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke='%239ca3af'%3E%3Cpath stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M19 9l-7 7-7-7'%3E%3C/path%3E%3C/svg%3E")`,
                  }}
                >
                  <option value="">Select</option>
                  {designations
                    .filter((d) => {
                      if (!formData.departmentId) return true;
                      return (
                        String(d.departmentId) === String(formData.departmentId)
                      );
                    })
                    .map((desig) => (
                      <option key={desig.id} value={desig.id}>
                        {desig.name}
                      </option>
                    ))}
                </select>
              </div>

              <div className="md:col-span-2">
                <label className="block text-sm font-semibold text-gray-700 mb-2">
                  About <span className="text-red-500">*</span>
                </label>
                <textarea
                  name="about"
                  required
                  rows={4}
                  value={formData.about}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#1a5f3f] focus:border-transparent transition-all resize-none"
                />
              </div>
            </div>
          </>
        )}

        {activeTab === "permissions" && (
          <div className="bg-gray-50 rounded-xl p-8 text-center text-gray-500">
            Permission settings will be available in the next update.
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex justify-end gap-4 pt-4">
          <button
            type="button"
            onClick={() => navigate("/employees")}
            className="px-10 py-3 border border-gray-200 text-gray-700 rounded-xl hover:bg-gray-50 transition-colors font-semibold"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={isLoading}
            className="px-10 py-3 bg-[#ff6b35] text-white rounded-xl hover:bg-[#e85a20] transition-colors font-semibold shadow-lg shadow-[#ff6b35]/20 disabled:opacity-50"
          >
            {isLoading ? "Saving..." : "Save"}
          </button>
        </div>
      </form>
    </div>
  );
}
